// Signal Failure — Indian Railway Accidents dataset
// Compiled from: Wikipedia "List of railway accidents and incidents in India";
// Ministry of Railways consequential-accident statistics (via dataful.in / indiastat.com).
// Coordinates are approximate (town/station level) for mapping purposes.
// Fatality figures vary across sources; the higher commonly-cited figure is used.

const DECADE_STATS = [
  { decade: "1961–70", collision: 834, derailment: 10664, levelCrossing: 1394, fire: 1037, other: 0, total: 13929 },
  { decade: "1971–80", collision: 588, derailment: 6763, levelCrossing: 1120, fire: 185, other: 0, total: 8665 },
  { decade: "1981–90", collision: 475, derailment: 6242, levelCrossing: 677, fire: 176, other: 0, total: 7570 },
  { decade: "1991–00", collision: 340, derailment: 3583, levelCrossing: 632, fire: 77, other: 0, total: 4642 },
  { decade: "2001–10", collision: 135, derailment: 1680, levelCrossing: 803, fire: 93, other: 52, total: 2763 },
  { decade: "2011–19", collision: 43, derailment: 567, levelCrossing: 352, fire: 54, other: 16, total: 1023 },
];

// cause codes: collision, derailment, fire, levelCrossing, bridge, sabotage, other
const INCIDENTS = [
  { date: "1902-09-12", name: "Kadapa district derailment", state: "Andhra Pradesh (Madras Presidency)", lat: 14.47, lng: 78.82, deaths: 100, cause: "derailment", note: "Bombay–Madras Mail derailed on a bridge near Mangapatnam." },
  { date: "1920-04-27", name: "Moradabad collision", state: "Uttar Pradesh", lat: 28.83, lng: 78.78, deaths: 120, cause: "collision", note: "Doon Express collided with a freight train." },
  { date: "1937-07-17", name: "Bihta derailment", state: "Bihar", lat: 25.55, lng: 84.9, deaths: 119, cause: "derailment", note: "Upper India Express plunged down an embankment." },
  { date: "1954-09-27", name: "Jangaon bridge derailment", state: "Telangana (Hyderabad State)", lat: 17.72, lng: 79.15, deaths: 136, cause: "bridge", note: "Derailment at a girder bridge." },
  { date: "1954-09-28", name: "Yasanti river bridge collapse", state: "Telangana", lat: 17.0, lng: 78.9, deaths: 139, cause: "bridge", note: "Bridge collapsed, train fell into the river south of Hyderabad." },
  { date: "1956-09-02", name: "Mahbubnagar bridge collapse", state: "Telangana", lat: 16.75, lng: 78.0, deaths: 125, cause: "bridge", note: "Bridge collapsed between Jadcherla and Mahbubnagar." },
  { date: "1956-11-23", name: "Ariyalur train accident", state: "Tamil Nadu", lat: 11.14, lng: 79.08, deaths: 104, cause: "bridge", note: "Madras–Tuticorin Express plunged into a flood-weakened embankment." },
  { date: "1962-07-22", name: "Dumraon collision", state: "Bihar", lat: 25.55, lng: 84.15, deaths: 100, cause: "collision", note: "Punjab Mail crashed into a freight train." },
  { date: "1963-07-22", name: "Tundla derailment", state: "Uttar Pradesh", lat: 27.2, lng: 78.25, deaths: 100, cause: "derailment", note: "Udyan Abha Toofan Express derailed at Etmadpur." },
  { date: "1964-12-23", name: "Pamban–Dhanushkodi cyclone", state: "Tamil Nadu", lat: 9.28, lng: 79.3, deaths: 126, cause: "other", note: "Passenger train washed away during the Rameswaram cyclone." },
  { date: "1966-06-13", name: "Matunga collision", state: "Maharashtra", lat: 19.03, lng: 72.85, deaths: 57, cause: "collision", note: "Two passenger trains collided near Matunga, Bombay." },
  { date: "1969-06-21", name: "Muhammadabad bridge derailment", state: "Uttar Pradesh", lat: 25.7, lng: 83.6, deaths: 70, cause: "bridge", note: "Coaches derailed and fell into the Magari River." },
  { date: "1969-07-14", name: "Jaipur collision", state: "Rajasthan", lat: 26.9, lng: 75.8, deaths: 85, cause: "collision", note: "Freight train crashed into a stationary passenger train." },
  { date: "1981-06-06", name: "Bihar train derailment (Bagmati)", state: "Bihar", lat: 25.75, lng: 86.47, deaths: 235, cause: "bridge", note: "Passenger train fell into the Bagmati River while crossing a bridge; some estimates run far higher." },
  { date: "1988-07-08", name: "Peruman railway accident", state: "Kerala", lat: 9.02, lng: 76.58, deaths: 105, cause: "bridge", note: "Island Express derailed on the Peruman bridge and fell into Ashtamudi Lake." },
  { date: "1990-04-16", name: "Patna shuttle fire", state: "Bihar", lat: 25.6, lng: 85.1, deaths: 70, cause: "fire", note: "Shuttle train caught fire near Patna." },
  { date: "1993-09-21", name: "Chhabra collision", state: "Rajasthan", lat: 24.67, lng: 76.15, deaths: 71, cause: "collision", note: "Passenger train collided with a freight train." },
  { date: "1995-08-20", name: "Firozabad rail disaster", state: "Uttar Pradesh", lat: 27.15, lng: 78.4, deaths: 358, cause: "collision", note: "Purushottam Express collided with the rear of the stationary Kalindi Express." },
  { date: "1997-08-15", name: "Coromandel Express collision", state: "Andhra Pradesh", lat: 17.7, lng: 83.3, deaths: 75, cause: "collision", note: "Up and down Coromandel Express trains collided near Visakhapatnam." },
  { date: "1997-09-14", name: "Bilaspur bridge collapse", state: "Chhattisgarh (Madhya Pradesh)", lat: 22.08, lng: 82.15, deaths: 81, cause: "bridge", note: "Ahmedabad–Howrah Express coaches plunged into a river." },
  { date: "1998-01-06", name: "Hardoi collision", state: "Uttar Pradesh", lat: 27.42, lng: 80.13, deaths: 70, cause: "collision", note: "Passenger train collided with the stationary Kashi Vishwanath Express." },
  { date: "1998-11-26", name: "Khanna rail disaster", state: "Punjab", lat: 30.71, lng: 76.22, deaths: 212, cause: "collision", note: "Sealdah–Jammu Tawi Express hit derailed coaches of the Golden Temple Mail." },
  { date: "1999-08-02", name: "Gaisal train disaster", state: "Assam", lat: 26.3, lng: 87.9, deaths: 285, cause: "collision", note: "Brahmaputra Mail collided head-on with the Avadh Assam Express." },
  { date: "2000-12-02", name: "Ambala–Ludhiana collision", state: "Punjab", lat: 30.9, lng: 75.85, deaths: 40, cause: "collision", note: "Amritsar Mail hit derailed freight-train coaches." },
  { date: "2001-06-22", name: "Kadalundi train derailment", state: "Kerala", lat: 11.13, lng: 75.82, deaths: 52, cause: "bridge", note: "Mangalore–Chennai Mail coaches fell into the Kadalundi River." },
  { date: "2002-06-04", name: "Kasganj level crossing disaster", state: "Uttar Pradesh", lat: 27.8, lng: 78.65, deaths: 30, cause: "levelCrossing", note: "Express train collided with a bus at an unstaffed crossing." },
  { date: "2002-09-09", name: "Rafiganj train wreck", state: "Bihar", lat: 24.77, lng: 84.63, deaths: 140, cause: "sabotage", note: "Howrah Rajdhani Express derailed on a bridge, suspected Naxalite sabotage." },
  { date: "2003-06-22", name: "Sindhudurg derailment", state: "Maharashtra", lat: 16.0, lng: 73.5, deaths: 52, cause: "derailment", note: "Special train coaches derailed near Karwar–Mumbai route." },
  { date: "2004-02-27", name: "Kanchenjunga Express level crossing", state: "West Bengal", lat: 25.9, lng: 88.15, deaths: 30, cause: "levelCrossing", note: "Collided with a truck at an unstaffed crossing." },
  { date: "2005-10-29", name: "Valigonda train wreck", state: "Andhra Pradesh", lat: 17.28, lng: 79.15, deaths: 114, cause: "bridge", note: "Delta Fast Passenger derailed after a flash-flood swept away a bridge." },
  { date: "2006-07-11", name: "Mumbai train bombings", state: "Maharashtra", lat: 19.0, lng: 72.85, deaths: 209, cause: "sabotage", note: "Coordinated bomb attacks on Mumbai suburban commuter trains." },
  { date: "2007-02-18", name: "Samjhauta Express bombings", state: "Haryana", lat: 29.4, lng: 76.95, deaths: 68, cause: "sabotage", note: "Bombs planted on the Samjhauta Express near Diwana, Panipat district." },
  { date: "2010-05-28", name: "Jnaneswari Express derailment", state: "West Bengal", lat: 22.4, lng: 87.15, deaths: 148, cause: "sabotage", note: "Derailed and was struck by an oncoming freight train; suspected sabotage." },
  { date: "2010-07-19", name: "Sainthia train collision", state: "West Bengal", lat: 23.95, lng: 87.65, deaths: 66, cause: "collision", note: "Uttar Banga Express collided with the Vananchal Express." },
  { date: "2011-07-10", name: "Fatehpur derailment", state: "Uttar Pradesh", lat: 25.93, lng: 80.81, deaths: 70, cause: "derailment", note: "Kalka Mail derailed in Fatehpur district." },
  { date: "2012-07-30", name: "Tamil Nadu Express fire", state: "Andhra Pradesh", lat: 14.44, lng: 79.98, deaths: 47, cause: "fire", note: "Fire broke out on the train near Nellore." },
  { date: "2013-08-19", name: "Dhamara Ghat train accident", state: "Bihar", lat: 26.15, lng: 86.6, deaths: 35, cause: "other", note: "Rajya Rani Express ran over passengers disembarking from another train." },
  { date: "2013-12-28", name: "Nanded Express fire", state: "Andhra Pradesh", lat: 14.13, lng: 77.55, deaths: 26, cause: "fire", note: "KSR Bengaluru–Hazur Sahib Nanded Express caught fire." },
  { date: "2014-05-26", name: "Gorakhdham Express collision", state: "Uttar Pradesh", lat: 26.77, lng: 83.07, deaths: 25, cause: "collision", note: "Collided with a stationary freight train near Khalilabad." },
  { date: "2014-07-23", name: "Medak district bus-train collision", state: "Telangana", lat: 17.87, lng: 78.27, deaths: 20, cause: "levelCrossing", note: "Passenger train collided with a school bus at an unstaffed crossing." },
  { date: "2015-03-20", name: "Rae Bareli derailment", state: "Uttar Pradesh", lat: 26.23, lng: 81.23, deaths: 58, cause: "derailment", note: "Dehradun–Varanasi Janta Express derailed." },
  { date: "2015-08-04", name: "Harda twin train derailment", state: "Madhya Pradesh", lat: 22.35, lng: 77.1, deaths: 31, cause: "bridge", note: "Two trains derailed after flash floods dislodged a culvert." },
  { date: "2016-11-20", name: "Pukhrayan train derailment", state: "Uttar Pradesh", lat: 26.23, lng: 79.85, deaths: 152, cause: "derailment", note: "Indore–Patna Express derailed near Pukhrayan, Kanpur Nagar district." },
  { date: "2017-01-21", name: "Kuneru train derailment", state: "Andhra Pradesh", lat: 18.5, lng: 83.4, deaths: 41, cause: "derailment", note: "Hirakhand Express derailed near Kuneru." },
  { date: "2017-08-19", name: "Khatauli train derailment", state: "Uttar Pradesh", lat: 29.28, lng: 77.72, deaths: 23, cause: "derailment", note: "Kalinga Utkal Express derailed near Khatauli." },
  { date: "2018-10-19", name: "Amritsar train disaster", state: "Punjab", lat: 31.63, lng: 74.87, deaths: 59, cause: "other", note: "Trains ran into a crowd watching Dussehra festivities on the tracks." },
  { date: "2023-06-02", name: "Odisha train collision (Balasore)", state: "Odisha", lat: 21.35, lng: 86.98, deaths: 296, cause: "collision", note: "Coromandel Express derailed after colliding with a stationary freight train and struck a passing Bengaluru–Howrah Express — India's deadliest rail crash since Firozabad." },
  { date: "2023-08-23", name: "Sairang bridge collapse", state: "Mizoram", lat: 23.55, lng: 92.6, deaths: 36, cause: "bridge", note: "Under-construction railway bridge collapsed on migrant workers." },
  { date: "2024-06-17", name: "West Bengal train collision (Rangapani)", state: "West Bengal", lat: 26.83, lng: 88.5, deaths: 11, cause: "collision", note: "Freight train hit the rear of the Kanchanjungha Express." },
  { date: "2025-01-22", name: "Jalgaon train accident", state: "Maharashtra", lat: 21.0, lng: 75.57, deaths: 12, cause: "other", note: "Passengers who disembarked after a false fire alarm were hit by an oncoming train." },
  { date: "2025-02-15", name: "New Delhi station stampede", state: "Delhi", lat: 28.64, lng: 77.22, deaths: 20, cause: "other", note: "Stampede during rush for a Prayagraj-bound train amid Maha Kumbh crowds." },
];
